name: "Podcast Generator"
author: "Ray Villalobos"
description: "Generates a podcast feed from a folder of MP3 files"
runs:
  using: "docker"
  main: "Dockerfile"
branding:
  icon: "git-branch"
  color: "red"
inputs:
  email:
    description: The commiter's email
    required: true
    default: ${{ github.actor }}@localhost
  name:
    description: The commiter's name
    required: true
    default: ${{ github.actor }}